# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tags',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='import_url',
            field=models.CharField(default='', help_text='Specify an URL to import HTML from', max_length=255, verbose_name='import_url'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=models.TextField(default='<body>\n<!-- Edit your newsletter here -->\n</body>', help_text='Newletter content', verbose_name='content'),
        ),
    ]
