# Generated by Django 2.1 on 2018-08-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoml', '0002_contact_unsubscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='contactmailingstatus',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aoml.Link', verbose_name='link'),
        ),
    ]
