# Generated by Django 3.2.1 on 2023-05-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoml', '0004_auto_20210516_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='unsubscribed',
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='unsubscribers',
            field=models.ManyToManyField(blank=True, related_name='mailinglist_unsubscriber', to='aoml.Contact', verbose_name='unsubscribers'),
        ),
    ]
