# Generated by Django 5.0.6 on 2026-08-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoml', '0006_mailinglist_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='header_reply',
            field=models.CharField(default='DJ Anael<contact@djanael.com>', max_length=255, verbose_name='reply to'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='header_sender',
            field=models.CharField(default='DJ Anael<soirees@djanael.com>', max_length=255, verbose_name='sender'),
        ),
    ]
